- name: Create  VM
  hosts: localhost
  connection: local
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
      state: present
      location: westus
      resource_group_name: table1jrwebapprg
      template_link: "https://raw.githubusercontent.com/jeff-rose/arm/master/template.json"
      parameters_link: "https://raw.githubusercontent.com/jeff-rose/arm/master/parameters.json"
