---
- name: something
  hosts: localhost
  vars_files:
    - vars.yml
  vars:
    webapp_name: "{{prefix}}webapp"
    location: westus
  tasks:
    - name: create rg
      azure_rm_resourcegroup:
        name: "{{group_name}}"
        location: "{{location}}"
    - name: create app svc
      azure_rm_webapp:
        resource_group: "{{group_name}}"
        name: "{{webapp_name}}"
        plan:
          resource_group: "{{group_name}}"
          name: "{{prefix}}appplan"
          is_linux: true
          sku: S1
          number_of_workers: 1
        frameworks:
          - name: "java"
            version: "8"
            settings:
              java_container: tomcat
              java_container_version: 8.5
              
